name: Learning CI
run-name: ${{github.actor}} is learning CI!

on:
  push:
    branches:
      - main
jobs:
  job-1:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        run: echo hello world
